chore: update README.md
synapseweb3/forcerelay pull request #329
Opened 2023-09-12 02:21 UTC by ashuralyk

Closes: #327 

## Description
change logs:
1. add unimplemented `--secret-key` option for `keys` command
2. update README.md doc

2023-09-14 06:06 UTC, Flouse requested changes

2023-09-14 06:06 UTC, Flouse commented on guide/src/templates/help_templates/keys/add.md
> +    forcerelay keys add [OPTIONS] --chain <CHAIN_ID> --secret-file <SECRET_FILE>
Sounds like line 9 is duplicated with line 5?

2023-09-14 06:22 UTC, Flouse commented on crates/relayer-cli/src/commands/keys/add.rs
>  /// The key-file and mnemonic-file flags can't be given at the same time, this will cause a terminating error.
```suggestion
/// The key-file, mnemonic-file, secret-file flags can't be given at the same time, this will cause a terminating error.
```

2023-09-14 09:08 UTC, Flouse commented on README.md
> +Forcerelay is an IBC-Compatible bridge that aims to open up the Nervos ecosystem and the Cosmos ecosystem, and it also serves as a standard cross-chain solution within the Nervos ecosystem.
```suggestion
Forcerelay is an IBC-Compatible bridge that aims to connect Nervos ecosystem and the Cosmos ecosystem, and it also serves as a standard cross-chain solution within the Nervos ecosystem.
```

2023-09-14 09:12 UTC, Flouse commented on README.md
> +Forcerelay is built on [Hermes](https://github.com/informalsystems/hermes), this means we will keep continue to track and update the latest version of Hermes, and won't stop it on any specific old ve
```suggestion
Forcerelay is built on [Hermes](https://github.com/informalsystems/hermes), and will continuously adapt to newer `Hermes` versions.
```

2023-09-14 09:14 UTC, Flouse commented on README.md
> +Forcerelay is actively under development, and we welcome any issues and pull requests. Here's an overview of our current progress:
```suggestion
Forcerelay is under active development, and we welcome any issues and pull requests. Here's an overview of our current progress:
```

2023-09-14 09:21 UTC, Flouse commented on README.md
> +We recommand you to download the pre-compiled binary, or you can compile mannully from the source code, which requires `Rust ^v1.56.0` installed:
```suggestion
We recommand you to download the pre-compiled binary, or you can compile mannully from the source code, which requires `Rust ^v1.72.0` installed:
```

2023-09-14 15:16 UTC, Flouse approved these changes
LGTM

2023-09-15 03:49 UTC, jjyr approved these changes

2023-09-15 03:50 UTC, merged