refactor: sync with axon new start commands
synapseweb3/forcerelay pull request #333
Opened 2023-09-26 02:48 UTC by wenyuanhust

Closes: #XXX

## Description

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Forcerelay) or unit/mock tests (for modules).
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

2023-09-26 03:25 UTC, Flouse requested changes

2023-09-26 03:25 UTC, Flouse commented on .github/workflows/ibc-test.yaml
> +      AXON_COMMIT: 7ae0a826647d07e0b25b4adb440a8c97231d6a04
Currently, the Axon version should contain this commit to [change the create contract limit config](https://github.com/axonweb3/axon/commit/56b1a218ea5ed0b84aae5e74422b4f77bcfc8b6e).

Would you try this Axon branch?
-> https://github.com/axonweb3/axon/commits/0.2.0-dev.1

2023-09-26 03:26 UTC, Flouse commented on .github/workflows/ibc-test.yaml
> +      AXON_COMMIT: 7ae0a826647d07e0b25b4adb440a8c97231d6a04
Related issue:
- https://github.com/synapseweb3/ibc-solidity-contract/issues/9

2023-10-16 03:56 UTC, Flouse requested changes, later dismissed
Please try to use the latest release of Axon.
@wenyuanhust

2023-10-23 04:45 UTC, ashuralyk commented
when we upgrade `axon-tools` dependency, the matched axon binary should be initialed with its new start command, so if we plan to test it in CI after the integration of `axon-tools`, this PR is needed to merge

2023-10-23 13:34 UTC, ashuralyk approved these changes

2023-10-23 14:21 UTC, blckngm approved these changes

2023-10-23 14:25 UTC, merged